In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report

In [5]:
csv=pd.read_csv("/content/heart.csv")

In [6]:
csv.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [7]:
csv.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [9]:
csv.shape

(1025, 14)

In [10]:
print("Columns name")
print(csv.columns.tolist())

Columns name
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [11]:
print("Datatypes and missing values")
csv.info()

Datatypes and missing values
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [12]:
print("Missing values per column")
print(csv.isnull().sum())

Missing values per column
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [13]:
print("Exact duplicate rows")
csv.duplicated().sum()

Exact duplicate rows

np.int64(723)

Now , we will check the distribution or target distribution in the original dataset

In [19]:
print("Original target distribution:")
print(csv["target"].value_counts().sort_index())

print("\nOriginal target percentages:")
print((csv["target"].value_counts(normalize=True) * 100).round(2))

Original target distribution:
target
0    499
1    526
Name: count, dtype: int64

Original target percentages:
target
1    51.32
0    48.68
Name: proportion, dtype: float64

now, lets create a copy without exact duplicate rows

In [21]:
csv_unique = csv.drop_duplicates().copy()

In [23]:
print("oringinal number of rows: ",len(csv))
print("rows after deleting duplicates: ",len(csv_unique))
print("duplicate occurences removed: ",len(csv)-len(csv_unique))

oringinal number of rows:  1025
rows after deleting duplicates:  302
duplicate occurences removed:  723

Compare target distribution after deduplication

In [25]:
print("Target distribution after deduplication: ")
print(csv_unique["target"].value_counts().sort_index())


print("\nTarget percentages after deduplication:")
print((csv_unique["target"].value_counts(normalize=True) * 100).round(2))

Target distribution after deduplication:
target
0    138
1    164
Name: count, dtype: int64

Target percentages after deduplication:
target
1    54.3
0    45.7
Name: proportion, dtype: float64

Now , we will seperate input features and target

In [26]:
X = csv_unique.drop("target",axis=1)
y = csv_unique["target"]

In [39]:
# we will be splitting the dataset into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42,stratify=y
)

print("Training feature shape: ",X_train.shape)
print("Testing feature shape: ",X_test.shape)

print("Training target distribution: ")
print(y_train.value_counts())

print("Testing target distribution: ")
print(y_test.value_counts())

Training feature shape:  (241, 13)
Testing feature shape:  (61, 13)
Training target distribution:
target
1    131
0    110
Name: count, dtype: int64
Testing target distribution:
target
1    33
0    28
Name: count, dtype: int64

# **MODEL: LOGISTIC REGRESSION**

In [42]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)

print("Actual values :",y_test.to_numpy())
print("Predicted values :",y_pred[:10])
print("Accuracy: ",round(accuracy * 100,2), "%")

Actual values : [0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 1 0
 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 0 1]
Predicted values : [0 1 0 1 1 0 1 0 1 1]
Accuracy:  80.33 %

In [51]:
print("Confusion matrix: ")
print(confusion_matrix(y_test,y_pred))

print("Classification Report: ")
print(classification_report(y_test,y_pred,zero_division=0))

Confusion matrix:
[[21  7]
 [ 5 28]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.75      0.78        28
           1       0.80      0.85      0.82        33

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61